-- ============================================================================
-- NaatuBite E-Commerce: Supabase Database Schema
-- Paste this script into your Supabase Dashboard -> SQL Editor and click "RUN"
-- ============================================================================

-- 1. CREATE ORDERS TABLE
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null,
  customer_name text not null,
  phone text not null,
  address text not null,
  items jsonb not null,
  subtotal numeric not null,
  delivery_fee numeric not null,
  total_amount numeric not null,
  payment_method text not null,
  status text default 'received',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.orders enable row level security;

-- Allow customer orders to be inserted via Supabase Publishable Key
drop policy if exists "Allow public order creation" on public.orders;
create policy "Allow public order creation" 
on public.orders 
for insert 
to anon, authenticated
with check (true);

-- Allow reading orders
drop policy if exists "Allow reading orders" on public.orders;
create policy "Allow reading orders" 
on public.orders 
for select 
to anon, authenticated
using (true);

-- 2. CREATE CONTACT INQUIRIES TABLE
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  subject text,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.contact_messages enable row level security;

-- Allow contact form submissions via Supabase Publishable Key
drop policy if exists "Allow public message submission" on public.contact_messages;
create policy "Allow public message submission" 
on public.contact_messages 
for insert 
to anon, authenticated
with check (true);

-- Allow reading contact messages
drop policy if exists "Allow reading contact messages" on public.contact_messages;
create policy "Allow reading contact messages" 
on public.contact_messages 
for select 
to anon, authenticated
using (true);
